// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfovtKf_iB2Kjhj4ac_3iOBEyrSfGpg2M',
    appId: '1:1028394492082:web:24184c1b26176537d269ab',
    messagingSenderId: '1028394492082',
    projectId: 'solmate-daa90',
    authDomain: 'solmate-daa90.firebaseapp.com',
    storageBucket: 'solmate-daa90.appspot.com',
    measurementId: 'G-PCEGGVX31T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_BcYAMQZXmPdfCz1kIGRY5LUQ9xDu40',
    appId: '1:1028394492082:android:58a13118a0cade8cd269ab',
    messagingSenderId: '1028394492082',
    projectId: 'solmate-daa90',
    storageBucket: 'solmate-daa90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkyd1dVa-CBys73towsV-LQTOaWHVb0cM',
    appId: '1:1028394492082:ios:f09be71e5e1f52a4d269ab',
    messagingSenderId: '1028394492082',
    projectId: 'solmate-daa90',
    storageBucket: 'solmate-daa90.appspot.com',
    iosBundleId: 'com.example.sneakersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkyd1dVa-CBys73towsV-LQTOaWHVb0cM',
    appId: '1:1028394492082:ios:f09be71e5e1f52a4d269ab',
    messagingSenderId: '1028394492082',
    projectId: 'solmate-daa90',
    storageBucket: 'solmate-daa90.appspot.com',
    iosBundleId: 'com.example.sneakersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfovtKf_iB2Kjhj4ac_3iOBEyrSfGpg2M',
    appId: '1:1028394492082:web:593a5f6109d647cbd269ab',
    messagingSenderId: '1028394492082',
    projectId: 'solmate-daa90',
    authDomain: 'solmate-daa90.firebaseapp.com',
    storageBucket: 'solmate-daa90.appspot.com',
    measurementId: 'G-N6NJP2PZ18',
  );
}
